name = "lottery-market"
version = "0.1.0"
description = "Demo market for Synthetix V3"

[setting.user]
defaultValue = "0x0A2f813621AD0C2Bbb6B6360109a47dfB79416aa"

[setting.jackpot]
defaultValue = "10000000000000000000"

[setting.ticketCost]
defaultValue = "1000000000000000000"

[setting.feePercent]
defaultValue = "10000000000000000"

[import.vrf]
source = "chainlink-vrf:2.0.0"

[import.synthetix]
source = "synthetix:latest"

[contract.LotteryMarket]
artifact = "LotteryMarket"
create2 = true
args = [
    "<%= imports.synthetix.contracts.CoreProxy.address %>",
    "<%= imports.vrf.imports.linkAggregator.imports.linkToken.contracts.Token.address %>",
    "<%= imports.vrf.contracts.VRFWrapper.address %>",
    "<%= settings.jackpot %>",
    "<%= settings.ticketCost %>",
    "<%= settings.feePercent %>"
]
depends = ["import.vrf", "import.synthetix"]

[invoke.registerMarket]
target = ["LotteryMarket"]
func = "registerMarket"
extra.marketId.event = "LotteryRegistered"
extra.marketId.arg = 0
depends = ["contract.LotteryMarket"]