name = "lottery-market"
version = "0.1.0"
description = "Demo market for Synthetix V3"

[setting.jackpot]
defaultValue = "1000000000000000000000"

[setting.ticketCost]
defaultValue = "1000000000000000000"

[setting.feePercent]
defaultValue = "10000000000000000"

[setting.salt]
defaultValue = "lottery"

[import.vrf]
source = "chainlink-vrf:2.0.0"

[import.synthetix]
source = "synthetix:3.1.0"

[contract.LotteryMarket]
artifact = "LotteryMarket"
create2 = true
args = [
    "<%= imports.synthetix.contracts.CoreProxy.address %>",
    "<%= imports.vrf.imports.linkAggregator.imports.linkToken.contracts.Token.address %>",
    "<%= imports.vrf.contracts.VRFWrapper.address %>",
    "<%= settings.jackpot %>",
    "<%= settings.ticketCost %>",
    "<%= settings.feePercent %>"
]
depends = ["import.vrf", "import.synthetix"]

[invoke.allowAllRegisterMarket]
target = ["synthetix.CoreProxy"]
fromCall.func = "owner"
func = "setFeatureFlagAllowAll"
args = [
  "<%= formatBytes32String('registerMarket') %>",
  true
]
depends = ["import.synthetix"]

[invoke.registerMarket]
target = ["LotteryMarket"]
func = "registerMarket"
from = "<%= settings.owner %>"
extra.marketId.event = "LotteryRegistered"
extra.marketId.arg = 0
depends = ["invoke.allowAllRegisterMarket", "contract.LotteryMarket"]
